### ISSUE TITLE
Error while calling OpenAI API

### ISSUE THREAD

**Issue by Nirsi** [UnknownEnergy/chatgpt-api#18]
Today, when I was using the wormchat, I started to get the following error message.
`404 This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?`

Interestingly, when I try to run the app locally, it works just fine

**Comment by UnknownEnergy** [comment]
It will try to use all endpoints depending on the model. Different model use different endpoints.
Which model do you use that causes this issue?
Have you tried clearing your browser cache? Maybe caching issue? But this also clears your chat history and api key for this browser!

**Comment by UnknownEnergy** [comment]
Or try using another browser/app

**Comment by Nirsi** [comment]
Hi, I'm sorry for the late response. I almost always use GPT-4-1106-preview as it is the cheapest and still the GPT -4 model. I tried clearing the cache and hard reloading, yet the error remains. I tried using Firefox and the mobile app as well without success.

**Comment by UnknownEnergy** [comment]
So I tried GPT-4-1106-preview myself now it works just fine.
Maybe try incognito mode in your browser or use a different browser. Also make sure to deactivated the "auto model switch" feature otherwise it will switch to GTP3.5-Turbo most of the time currently.
Can you use any other model without issues? Maybe your account / open-ai key is not allowed anymore to use this model?

**Comment by UnknownEnergy** [comment]
otherwise try another gtp4 model if it works then probably your account does not have access to it anymore. I would suggest try another tool with your api key or contact OpenAI support in this case.

**Comment by Nirsi** [comment]
Well, it seems that Chatworm started working again, but I have no idea why it started working again. So the issue can be closed.
